### ISSUE TITLE
Blank landing page

### ISSUE THREAD

**Issue by scottwarren** [nozzle/nozzle.io#11]
![image](https://user-images.githubusercontent.com/2718494/52208883-c78cc480-288a-11e9-9cbb-2c8c45949a83.png)

For some reason I get a blank page when navigating my browser to your home page.

Chrome version: `72.0.3626.81 (Official Build) (64-bit)`
MacOS version: `10.14.3`

No errors in console, other than warnings from Google Analytics about not using `document.write`

**Comment by scottwarren** [comment]
![image](https://user-images.githubusercontent.com/2718494/52208940-03278e80-288b-11e9-9cdc-02c514738686.png)

**Comment by tannerlinsley** [comment]
Fixed
