### ISSUE TITLE
Make the delorean animations work on the About page

### ISSUE THREAD

**Issue by nathanburrblair** [nozzle/nozzle.io#232]
And the text animations.

**Comment by tannerlinsley** [comment]
This whole page is... outdated. My vote is to ditch the timeline and have a normal about page. And retake our company photo.

**Comment by boydnorwood** [comment]
Ian wrote up some content for this page awhile back, fyi. It is probably in Asana.

**Comment by nathanburrblair** [comment]
I reworked the page. Still don't have a new company photo, but we can add it when we have it. Closing this.
