### ISSUE TITLE
homepage: customer logos have uneven spacing

### ISSUE THREAD

**Issue by derekperkins** [nozzle/nozzle.io#241]
I know this is a difficult problem to solve, since they're all different shapes / sizes. Not a blocking issue by any means

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/3588778/235213233-3540270c-c189-43a0-8f33-d9c6b09dd1cd.png">

**Comment by nathanburrblair** [comment]
Fixed, and made them scroll horizontally on mobile.
