### ISSUE TITLE
(MOST URGENT in this list): Fix styling when embedding tweets into posts

### ISSUE THREAD

**Issue by boydnorwood** [nozzle/nozzle.io#26]
Jake,

URGENT (sort of) because I want to publish a post soon containing many embedded tweets.

I want to embed the following tweet into a blog post: https://twitter.com/Jammer_Volts/status/1095150399034601473

When I click on the dropdown and click Embed Tweet, I get the following code: 
`<blockquote class="twitter-tweet" data-theme="light"><p lang="en" dir="ltr">Disallow: * <a href="https://t.co/Y3FerumPmW">pic.twitter.com/Y3FerumPmW</a></p>&mdash; Jamie Alberico (@Jammer_Volts) <a href="https://twitter.com/Jammer_Volts/status/1095150399034601473?ref_src=twsrc%5Etfw">February 12, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

When I paste it into my blog post, it doesn't show the image and it just doesn't look the way it's supposed to look. It's pasted in the following blog post that is unpublished: https://app.contentful.com/spaces/z8uwv83tofbw/entries/1rdXEOa8xOHFwOcy4Yfkwz. 

I published the post for a second to take a screenshot of what it will look like and you can see that here: https://share.getcloudapp.com/04uKOe4D

A couple of examples of how normal twitter embeds look:

- https://kaiserthesage.com/about/ scroll down and you'll see 4 embedded tweets
- https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview Maybe twitter's documentation on this page can help you solve the problem.

**Comment by boydnorwood** [comment]
I'd really prefer to have the embedded tweet look just like it does on the two examples above, meaning they don't include any thing above or below the lines of the box.

**Comment by boydnorwood** [comment]
Here is a blog post that just came out that appears to use their own styling for tweets they were quoting. https://www.semrush.com/blog/common-seo-mistakes-how-to-avoid-them/

Would setting up something like this be easier?

**Comment by tannerlinsley** [comment]
Fixed via Google Tag Manager
