### ISSUE TITLE
Site content backup

### ISSUE THREAD

**Issue by boydnorwood** [nozzle/nozzle.io#31]
Jake,

On wordpress, you can install aplugin that will send backup files to your email or dropbox or somwhere on a schedule.

Can you search to see if their is a content backup solution for Contentful please?

Let me know what you find before spending the time to actually implement. We'll want something eventually but depending on how much time it will take to implement, we'll decide on when to tackle the implementation.

**Comment by jtribe32** [comment]
Here is what i found on their website at https://www.contentful.com/faq/backup-security-and-hosting/#where-s-contentful-being-hosted

**Can I backup my data offsite?**
We always do backups of all the content ourselves. You can always use the Content Delivery API (CDA) to export all of the content manually.

As far as i can tell there is not a service that will send us a backup like wordpress. We would just have to set it up ourselves using their API. I can keep looking if you want though.
