### ISSUE TITLE
Fix our xml sitemap page

### ISSUE THREAD

**Issue by boydnorwood** [nozzle/nozzle.io#46]
nozzle.io/sitemap.xml goes to a 404 page right now. It used to work but broke last fall for some reason.

Please fix it.

You can use the attached xml file from the following task if you need: https://app.asana.com/0/1111870931558592/1135540899276584

**Comment by tannerlinsley** [comment]
Jake and I just fixed this error with this deployment: 65d30a759ed9cb53976152f93d6f2e781294cc3b
