### ISSUE TITLE
Hit Pingomatic on page/post publish like WordPress

### ISSUE THREAD

**Issue by derekperkins** [nozzle/nozzle.io#56]
Not sure exactly how WordPress does it, but some XMLRPC business. Hopefully this gets our pages indexed faster

**Comment by jtribe32** [comment]
I added a webhook on Contentful that will hit pingomatic when we publish or unpublish any blog posts.

**Comment by derekperkins** [comment]
Is that only blog posts or for any pages?

**Comment by jtribe32** [comment]
That's only for blog posts
