### ISSUE TITLE
Add Metrics Page

### ISSUE THREAD

**Issue by derekperkins** [nozzle/nozzle.io#99]
I created a new content type in Contentful to describe our metrics. I'd like to create a page that lists them all out to help as we increase our marketing.

https://app.contentful.com/spaces/z8uwv83tofbw/entries?id=FQkVE1G6F5FoDhVk&order.fieldId=updatedAt&order.direction=descending&login=1&contentTypeId=metrics&displayedFieldIds=contentType&displayedFieldIds=updatedAt&displayedFieldIds=author

**Comment by jtribe32** [comment]
Good idea. Do you want the new metrics page to be a top level nav bar page? Do you have any suggestions on how you would like the page to look?

**Comment by jtribe32** [comment]
fixed by https://github.com/nozzle/nozzle.io/pull/103
